---
# Copyright 2019 gbazack
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for deploying 1 Custom VPC consisted of 1 subnet'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC parameters'
      Parameters:
      - subnetcidrBlock1
      - AvailabilityZones1
Parameters:      
  subnetcidrBlock1:
    Description: 'CidrBlock of subnets - 10.0.subnetcidrBlock1.0/24'
    Type: Number
    Default: 1
    ConstraintDescription: 'Must be in the range [1-9]'
    MinValue: 1
    MaxValue: 9
  AvailabilityZones1:
    Description: 'List of Availability zones'
    Type: 'AWS::EC2::AvailabilityZone::Name'
    Default: String
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: 'default'
      Tags:
        - Key: 'Name'
          Value: 'VPC-1az'
#Internet Gateway
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'IGW-VPC'
#VPC Gateway Attachment
  GatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
#Creation of Subnets
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Sub '10.0.${subnetcidrBlock1}.0/24'
      AvailabilityZone:
        Ref: AvailabilityZones1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: 'Name'
          Value: 'PublicSubnet-VPC'
#RouteTables
  RouteTablePublic:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: 'Name'
          Value: 'RTpublic-VPC'           
#RouteTable configuration
  RoutePublic:
    DependsOn: GatewayAttachment
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        Ref: InternetGateway           
#Subnet RouteTable Association
  RouteTableAssociationPublic:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: RouteTablePublic
  NetworkAclPublic:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: 'Name'
          Value: 'public-acl'
  NetworkAclAssociationPublic:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId:
        Ref: PublicSubnet
      NetworkAclId:
        Ref: NetworkAclPublic
  NetworkAclPublicEntryIn:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId:
        Ref: NetworkAclPublic
      RuleNumber: 100
      Protocol: -1
      RuleAction: Allow
      Egress: false
      CidrBlock: '0.0.0.0/0'
  NetworkAclPublicEntryOut:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId:
        Ref: NetworkAclPublic
      RuleNumber: 100
      Protocol: -1
      RuleAction: Allow
      Egress: true
      CidrBlock: '0.0.0.0/0'
Outputs:
  TemplateID:
    Description: 'VPC-1az1 template Id'
    Value: 'vpc/vpc-1az1'
  TemplateVersion:
    Description: 'VPC-1az1 template Version'
    Value: '__VERSION__'
  StackName:
    Description: 'stack name'
    Value: !Sub '${AWS::StackName}'
  AvailabilityZones:
    Description: 'Availability Zones'
    Value: !Ref AvailabilityZones1
    Export:
      Name: !Sub '${AWS::StackName}-AvailabilityZones'
  CidrBlock:
    Description: 'The set of IP addresses for the VPC.'
    Value: !GetAtt 'VPC.CidrBlock'
    Export:
      Name: !Sub '${AWS::StackName}-CidrBlock'
  VPC:
    Description: 'The Custom VPC'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC'
  PublicSubnet:
    Description: 'Public subnet.'
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet'
  RouteTablePublic:
    Description: 'Public route table'
    Value: !Ref RouteTablePublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTablePublic'
